# Generated by Django 3.1 on 2020-11-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.page')),
            ],
        ),
        migrations.CreateModel(
            name='Kanban_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.kanban')),
            ],
        ),
        migrations.CreateModel(
            name='Kanban_Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('kanban_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.kanban_group')),
            ],
        ),
        migrations.AddField(
            model_name='kanban',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.page'),
        ),
    ]
