# Generated by Django 3.1 on 2020-11-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_auto_20201121_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat_app.user'),
            preserve_default=False,
        ),
    ]
