# Generated by Django 3.1 on 2020-12-05 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_heading_1_page_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heading_1',
            name='page_element',
        ),
        migrations.AddField(
            model_name='page_element',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='element', to='chat_app.heading_1'),
        ),
        migrations.AlterField(
            model_name='page_element',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_elements', to='chat_app.page'),
        ),
    ]
