# Generated by Django 3.1 on 2020-12-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0008_auto_20201205_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_element',
            name='element',
        ),
        migrations.AddField(
            model_name='heading_1',
            name='page_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='heading_1s', to='chat_app.page_element'),
            preserve_default=False,
        ),
    ]
