# Generated by Django 3.1 on 2020-12-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0009_auto_20201205_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='heading_1',
            name='element_type',
            field=models.CharField(default='Heading_1', max_length=85),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='heading_1',
            name='page_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_1', to='chat_app.page_element'),
        ),
    ]
