# Generated by Django 3.1 on 2020-12-05 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_auto_20201205_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading_1',
            name='page_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='chat_app.page_element'),
        ),
    ]
