# Generated by Django 3.1 on 2020-12-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0012_auto_20201205_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading_1',
            name='page_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_1', to='chat_app.page_element'),
        ),
        migrations.CreateModel(
            name='Heading_2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_text', models.CharField(max_length=85)),
                ('page_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_2', to='chat_app.page_element')),
            ],
        ),
    ]
