# Generated by Django 3.1 on 2020-12-20 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0016_auto_20201212_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heading_2',
            name='heading_text',
            field=models.CharField(blank=True, max_length=85, null=True),
        ),
    ]
