# Generated by Django 3.1 on 2020-12-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0018_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
