# Generated by Django 3.1 on 2021-01-21 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0019_auto_20201223_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanban',
            name='page',
        ),
        migrations.AddField(
            model_name='kanban',
            name='page_element',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kanban', to='chat_app.page_element'),
            preserve_default=False,
        ),
    ]
