# Generated by Django 3.1 on 2021-01-21 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0020_auto_20210121_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban_group',
            name='kanban',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_group', to='chat_app.kanban'),
        ),
    ]
