# Generated by Django 3.1 on 2021-01-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0021_auto_20210121_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban_card',
            name='kanban_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_card', to='chat_app.kanban_group'),
        ),
    ]
