# Generated by Django 3.1 on 2021-01-24 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0022_auto_20210121_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban_card',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
