# Generated by Django 3.1 on 2021-01-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0023_auto_20210124_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
