# Generated by Django 3.1 on 2021-01-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0024_auto_20210124_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanban_card',
            name='order_on_group',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
