# Generated by Django 3.1 on 2021-01-31 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0028_pagelink_page_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelink',
            name='page_name',
        ),
        migrations.AddField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat_app.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='page_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_link', to='chat_app.page_element'),
        ),
    ]
