# Generated by Django 3.1 on 2021-01-31 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0030_auto_20210131_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='page_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='page_link', to='chat_app.page_element'),
        ),
    ]
