# Generated by Django 3.1 on 2021-01-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0031_auto_20210131_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat_app.page'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='page_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_link', to='chat_app.page_element'),
        ),
    ]
