# Generated by Django 3.1 on 2021-01-31 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0032_auto_20210131_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_app.page'),
        ),
    ]
