# Generated by Django 3.1 on 2021-02-06 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0035_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column', to='chat_app.table')),
            ],
        ),
    ]
