# Generated by Django 3.1 on 2021-02-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0036_table_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_column',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='chat_app.table'),
        ),
        migrations.CreateModel(
            name='Table_row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('table_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='chat_app.table_column')),
            ],
        ),
    ]
