# Generated by Django 3.1 on 2021-02-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0037_auto_20210206_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('table_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='chat_app.table_data')),
            ],
        ),
        migrations.RemoveField(
            model_name='table_row',
            name='description',
        ),
        migrations.RemoveField(
            model_name='table_row',
            name='table_column',
        ),
        migrations.AddField(
            model_name='table_row',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='chat_app.table'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Table_column',
        ),
    ]
