# Generated by Django 3.1 on 2021-02-06 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0038_auto_20210206_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table_data',
            name='table_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='chat_app.table_row'),
        ),
    ]
