# Generated by Django 3.1 on 2021-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0039_auto_20210206_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data',
            name='header',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
