# Generated by Django 3.1 on 2021-02-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0040_table_data_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
