# Generated by Django 3.1 on 2021-02-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0042_table_data_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_row',
            name='order',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
