# Generated by Django 3.1 on 2021-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0043_table_row_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data',
            name='property_type',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
