# Generated by Django 3.1 on 2021-02-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0044_table_data_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data',
            name='checkbox',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_data',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='table_data',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
