# Generated by Django 3.1 on 2021-02-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0046_auto_20210211_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_data',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
