# Generated by Django 3.1 on 2021-02-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0049_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='shown',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='table_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='chat_app.table_data'),
        ),
    ]
