# Generated by Django 3.1 on 2021-02-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0050_auto_20210214_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='shown',
        ),
    ]
