# Generated by Django 3.1 on 2021-02-15 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0051_remove_tag_shown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='table_data',
        ),
        migrations.AddField(
            model_name='tag',
            name='table_data',
            field=models.ManyToManyField(related_name='tags', to='chat_app.Table_data'),
        ),
    ]
