# Generated by Django 3.1 on 2021-02-15 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0052_auto_20210215_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='table_head',
            field=models.ForeignKey(default=749, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='chat_app.table_data'),
            preserve_default=False,
        ),
    ]
