# Generated by Django 3.1 on 2021-02-15 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0053_tag_table_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='table_data',
            field=models.ManyToManyField(blank=True, related_name='tags', to='chat_app.Table_data'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='table_head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_heads', to='chat_app.table_data'),
        ),
    ]
