# Generated by Django 3.1 on 2021-02-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0054_auto_20210215_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='blue', max_length=100),
            preserve_default=False,
        ),
    ]
