# Generated by Django 3.1 on 2021-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0058_auto_20210221_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='groups',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
