# Generated by Django 3.1 on 2021-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0060_remove_page_element_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_element',
            name='column',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
