# Generated by Django 3.1 on 2021-03-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0062_kanban_group_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_element',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
