# Generated by Django 3.1 on 2021-04-27 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0064_auto_20210427_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='chat_app.page'),
        ),
        migrations.DeleteModel(
            name='Page_two',
        ),
    ]
