# Generated by Django 3.1 on 2021-04-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0065_auto_20210427_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
    ]
