# Generated by Django 3.2.11 on 2022-06-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page_element',
            name='column',
        ),
        migrations.RemoveField(
            model_name='page_element',
            name='group',
        ),
    ]
