# Generated by Django 3.2.11 on 2022-06-27 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220617_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='groups',
        ),
    ]
