# Generated by Django 3.2.11 on 2022-08-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_page_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='closed',
            field=models.BooleanField(null=True),
        ),
    ]
